
import React from 'react';
import type { Draft } from '../types';
import { FileText, Send, Spinner } from './Icons';

interface DraftsListProps {
    drafts: Draft[];
    onSelectDraft: (draft: Draft) => void;
    onPublish: (id: number) => void;
    publishingId: number | null;
}

export const DraftsList: React.FC<DraftsListProps> = ({ drafts, onSelectDraft, onPublish, publishingId }) => {
    return (
        <div className="aca-fade-in">
            <div className="aca-page-header">
                <h1 className="aca-page-title">Content Drafts</h1>
                <p className="aca-page-description">Here are the articles generated by the AI. Review and publish them.</p>
            </div>

            <div className="aca-card">
                {drafts.length > 0 ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                        {drafts.map(draft => {
                            const isPublishing = publishingId === draft.id;
                            return (
                                <div
                                    key={draft.id}
                                    style={{
                                        background: '#f6f7f7',
                                        padding: '20px',
                                        borderRadius: '4px',
                                        border: '1px solid #ccd0d4',
                                        display: 'flex',
                                        flexDirection: 'column',
                                        gap: '15px',
                                        alignItems: 'center',
                                        transition: 'all 0.3s ease',
                                        opacity: isPublishing ? 0.5 : 1,
                                        transform: isPublishing ? 'scale(0.98)' : 'scale(1)',
                                        cursor: isPublishing ? 'not-allowed' : 'auto'
                                    }}
                                    onMouseEnter={(e) => {
                                        if (!isPublishing) {
                                            e.currentTarget.style.background = '#f0f0f1';
                                        }
                                    }}
                                    onMouseLeave={(e) => {
                                        if (!isPublishing) {
                                            e.currentTarget.style.background = '#f6f7f7';
                                        }
                                    }}
                                >
                                    <div 
                                        style={{ 
                                            flexGrow: 1, 
                                            textAlign: 'center', 
                                            cursor: isPublishing ? 'not-allowed' : 'pointer',
                                            width: '100%'
                                        }} 
                                        onClick={() => !isPublishing && onSelectDraft(draft)}
                                    >
                                        <h3 style={{ 
                                            fontSize: '18px', 
                                            fontWeight: '600', 
                                            color: '#23282d', 
                                            margin: '0 0 8px 0' 
                                        }}>
                                            {draft.title}
                                        </h3>
                                        <p style={{ 
                                            fontSize: '13px', 
                                            color: '#646970', 
                                            margin: 0 
                                        }}>
                                            Created: {new Date(draft.createdAt).toLocaleDateString()}
                                        </p>
                                    </div>
                                    <div style={{ 
                                        display: 'flex', 
                                        alignItems: 'center', 
                                        gap: '10px', 
                                        flexShrink: 0,
                                        flexWrap: 'wrap',
                                        justifyContent: 'center'
                                    }}>
                                        <button
                                            onClick={() => onSelectDraft(draft)}
                                            disabled={isPublishing}
                                            className="aca-button secondary"
                                            style={{ 
                                                fontSize: '13px',
                                                padding: '8px 16px'
                                            }}
                                        >
                                            View Draft
                                        </button>
                                        <button
                                            onClick={() => onPublish(draft.id)}
                                            disabled={isPublishing}
                                            className="aca-button"
                                            style={{ 
                                                display: 'flex', 
                                                alignItems: 'center', 
                                                gap: '8px',
                                                fontSize: '13px',
                                                padding: '8px 16px',
                                                background: isPublishing ? '#f6f7f7' : '#00a32a',
                                                borderColor: isPublishing ? '#ccd0d4' : '#00a32a',
                                                color: isPublishing ? '#a7aaad' : '#ffffff',
                                                cursor: isPublishing ? 'wait' : 'pointer',
                                                minWidth: '140px',
                                                justifyContent: 'center'
                                            }}
                                            onMouseEnter={(e) => {
                                                if (!isPublishing) {
                                                    e.currentTarget.style.background = '#008a20';
                                                    e.currentTarget.style.borderColor = '#008a20';
                                                }
                                            }}
                                            onMouseLeave={(e) => {
                                                if (!isPublishing) {
                                                    e.currentTarget.style.background = '#00a32a';
                                                    e.currentTarget.style.borderColor = '#00a32a';
                                                }
                                            }}
                                        >
                                            {isPublishing ? (
                                                <>
                                                    <Spinner style={{ width: '16px', height: '16px', marginRight: '8px' }} />
                                                    Publishing...
                                                </>
                                            ) : (
                                                <>
                                                    <Send style={{ width: '14px', height: '14px' }} />
                                                    Publish
                                                </>
                                            )}
                                        </button>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                ) : (
                    <div style={{ 
                        textAlign: 'center', 
                        padding: '60px 20px', 
                        color: '#646970', 
                        border: '2px dashed #ccd0d4', 
                        borderRadius: '4px' 
                    }}>
                        <FileText style={{ margin: '0 auto 15px auto', width: '48px', height: '48px', fill: '#a7aaad' }} />
                        <p style={{ margin: '0 0 5px 0', fontSize: '16px', fontWeight: '500', color: '#23282d' }}>No drafts have been created yet.</p>
                        <p style={{ margin: 0, fontSize: '13px' }}>Go to the Idea Board to create your first draft.</p>
                    </div>
                )}
            </div>
        </div>
    );
};
