
import React from 'react';
import type { Draft } from '../types';
import { FileText, Send, Spinner } from './Icons';

interface DraftsListProps {
    drafts: Draft[];
    onSelectDraft: (draft: Draft) => void;
    onPublish: (id: number) => void;
    publishingId: number | null;
}

export const DraftsList: React.FC<DraftsListProps> = ({ drafts, onSelectDraft, onPublish, publishingId }) => {
    return (
        <div className="space-y-6">
            <header>
                <h2 className="text-3xl font-bold text-white border-b border-slate-700 pb-3 mb-6">Content Drafts</h2>
                <p className="text-slate-400 -mt-2">Here are the articles generated by the AI. Review and publish them.</p>
            </header>

            <div className="bg-slate-800 p-4 sm:p-6 rounded-lg border border-slate-700/80">
                {drafts.length > 0 ? (
                    <div className="space-y-3">
                        {drafts.map(draft => {
                            const isPublishing = publishingId === draft.id;
                            return (
                                <div
                                    key={draft.id}
                                    className={`
                                        bg-slate-900/50 p-4 rounded-lg border border-slate-700 flex flex-col sm:flex-row gap-4 justify-between items-center
                                        transition-all duration-300
                                        ${isPublishing ? 'opacity-50 scale-95' : 'hover:bg-slate-700/50'}
                                    `}
                                >
                                    <div className="flex-grow text-center sm:text-left cursor-pointer" onClick={() => !isPublishing && onSelectDraft(draft)}>
                                        <h3 className="text-lg font-semibold text-white">{draft.title}</h3>
                                        <p className="text-sm text-slate-400">Created: {new Date(draft.createdAt).toLocaleDateString()}</p>
                                    </div>
                                    <div className="flex items-center space-x-2 flex-shrink-0">
                                        <button
                                            onClick={() => onSelectDraft(draft)}
                                            disabled={isPublishing}
                                            className="bg-slate-600 text-white px-4 py-2 rounded-md text-sm font-semibold hover:bg-slate-700 transition-colors disabled:opacity-70 disabled:cursor-not-allowed"
                                        >
                                            View Draft
                                        </button>
                                        <button
                                            onClick={() => onPublish(draft.id)}
                                            disabled={isPublishing}
                                            className="bg-green-600 text-white px-4 py-2 rounded-md text-sm font-semibold hover:bg-green-700 transition-colors flex items-center gap-2 disabled:bg-green-800 disabled:cursor-wait min-w-[140px] justify-center"
                                        >
                                            {isPublishing ? (
                                                <>
                                                    <Spinner className="h-5 w-5 mr-2" />
                                                    Publishing...
                                                </>
                                            ) : (
                                                <>
                                                    <Send className="h-4 w-4" />
                                                    Publish
                                                </>
                                            )}
                                        </button>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                ) : (
                    <div className="text-center py-16 text-slate-500 border-2 border-dashed border-slate-700 rounded-md">
                        <FileText className="mx-auto h-12 w-12 text-slate-600" />
                        <p className="mt-4 text-lg font-medium">No drafts have been created yet.</p>
                        <p>Go to the Idea Board to create your first draft.</p>
                    </div>
                )}
            </div>
        </div>
    );
};
